services:
  jobmanager:
    image: flink:2.2.0-scala_2.12
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./conf:/opt/flink/conf:ro

  taskmanager-1:
    image: flink:2.2.0-scala_2.12
    container_name: flink-taskmanager-1
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./conf:/opt/flink/conf:ro

  taskmanager-2:
    image: flink:2.2.0-scala_2.12
    container_name: flink-taskmanager-2
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./conf:/opt/flink/conf:ro
